# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: server_services.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'server_services.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15server_services.proto\x12\x0fserver_services\"I\n\x13SendFileRequestBody\x12\x0c\n\x04\x66ile\x18\x01 \x01(\x0c\x12\x11\n\tfile_mime\x18\x02 \x01(\t\x12\x11\n\tfile_name\x18\x03 \x01(\t\"\'\n\x14SendFileResponseBody\x12\x0f\n\x07success\x18\x01 \x01(\x08\"8\n\x15SendFileChunksRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x11\n\tfile_name\x18\x02 \x01(\t\":\n\x16SendFileChunksResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"$\n\x0f\x43svToXmlRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\"4\n\x10\x43svToXmlResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"8\n\x10\x46ilterXmlRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x11\n\tcity_name\x18\x02 \x01(\t\"G\n\x11\x46ilterXmlResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x10\n\x08xml_data\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t2\xf4\x02\n\x0fSendFileService\x12W\n\x08SendFile\x12$.server_services.SendFileRequestBody\x1a%.server_services.SendFileResponseBody\x12\x63\n\x0eSendFileChunks\x12&.server_services.SendFileChunksRequest\x1a\'.server_services.SendFileChunksResponse(\x01\x12O\n\x08\x43svToXml\x12 .server_services.CsvToXmlRequest\x1a!.server_services.CsvToXmlResponse\x12R\n\tFilterXml\x12!.server_services.FilterXmlRequest\x1a\".server_services.FilterXmlResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_services_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENDFILEREQUESTBODY']._serialized_start=42
  _globals['_SENDFILEREQUESTBODY']._serialized_end=115
  _globals['_SENDFILERESPONSEBODY']._serialized_start=117
  _globals['_SENDFILERESPONSEBODY']._serialized_end=156
  _globals['_SENDFILECHUNKSREQUEST']._serialized_start=158
  _globals['_SENDFILECHUNKSREQUEST']._serialized_end=214
  _globals['_SENDFILECHUNKSRESPONSE']._serialized_start=216
  _globals['_SENDFILECHUNKSRESPONSE']._serialized_end=274
  _globals['_CSVTOXMLREQUEST']._serialized_start=276
  _globals['_CSVTOXMLREQUEST']._serialized_end=312
  _globals['_CSVTOXMLRESPONSE']._serialized_start=314
  _globals['_CSVTOXMLRESPONSE']._serialized_end=366
  _globals['_FILTERXMLREQUEST']._serialized_start=368
  _globals['_FILTERXMLREQUEST']._serialized_end=424
  _globals['_FILTERXMLRESPONSE']._serialized_start=426
  _globals['_FILTERXMLRESPONSE']._serialized_end=497
  _globals['_SENDFILESERVICE']._serialized_start=500
  _globals['_SENDFILESERVICE']._serialized_end=872
# @@protoc_insertion_point(module_scope)
